### ISSUE TITLE
Unable to load POM

### ISSUE THREAD

**Issue by Groquike** [Null-MC/Shrimple#142]
Using AVPBR Retextured R5 with 1.21.5 Minecraft version

Here is the error message:

crumbling: crumbling: ERROR: 0:403: 'GetParallaxCoord' : no matching overloaded function found 
ERROR: 0:403: 'assign' :  cannot convert from ' const float' to ' temp 2-component vector of float'
ERROR: 0:403: '' : compilation terminated 
ERROR: 3 compilation errors.  No code generated.

I would love to be able to admire the beautiful parallax occlusion that this resource pack offers with this beautiful shader </3

Keep up the goord work !

**Comment by null511** [comment]
Try the latest in-development version, iirc that was already fixed.
https://github.com/Null-MC/Shrimple/archive/refs/heads/main.zip

**Comment by Schweeeeeeeeeeeeeeee** [comment]
isnt fixed when i tried it
crumbling: crumbling: 0:403(14): error: no matching function for call to `GetParallaxCoord(vec2, mat2, vec3, float, float, vec3)'; candidates are:
0:403(14): error:    vec2 GetParallaxCoord(vec2, float, vec3, float, float, vec3)
still dying at line 403

**Comment by meisme-dev** [comment]
I had this issue on Zink but switching to regular OpenGL drivers fixed it, it seems to be a driver issue.
